name: Deployment Pipeline



on:
  push:
    branches:
    - master
  
jobs:
    deploy:
      runs-on: ubuntu-18.04
      steps: 
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0  # último commit 
        - uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install dependencies
            run: npm install
        - name: npm run eslint
